/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/provider-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviderProfiles"];
        put?: never;
        post: operations["createProviderProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/provider-profiles/{providerID}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testProviderProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModelProfiles"];
        put?: never;
        post: operations["createModelProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model-profiles/{modelID}/default": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelID: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setDefaultModelProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policy-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPolicyProfiles"];
        put?: never;
        post: operations["createPolicyProfileVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policy-profiles/{policyID}/default": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyID: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setDefaultPolicyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policy-profiles/{policyID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deactivatePolicyProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get: operations["getProjectWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get: operations["listProjectFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get: operations["readProjectFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/v1/sessions/{sessionID}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get: operations["listSessionMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/artifacts/{artifactID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                artifactID: string;
            };
            cookie?: never;
        };
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/artifacts/{artifactID}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                artifactID: string;
            };
            cookie?: never;
        };
        get: operations["previewArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/artifacts/{artifactID}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                artifactID: string;
            };
            cookie?: never;
        };
        get: operations["downloadArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get: operations["listSessionBranches"];
        put?: never;
        post: operations["createSessionBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/branches/{branchID}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                branchID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateSessionBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get: operations["getSessionRecovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/active-run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get: operations["getSessionActiveRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/attachments/images": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadImageAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/compactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get: operations["listContextCompactions"];
        put?: never;
        post: operations["createContextCompaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compactions/{compactionID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compactionID: string;
            };
            cookie?: never;
        };
        get: operations["getContextCompaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runID}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runID}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runID}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["queueRunInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approval-requests/{approvalID}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approvalID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideToolApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runID}/events": {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            data?: unknown;
        };
        HealthEnvelope: {
            data: {
                /** @enum {string} */
                status: "live" | "ready";
                sandbox?: string;
                degraded?: boolean;
            };
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                requestId: string;
                retryable: boolean;
            };
        };
        ProviderProfile: {
            id: string;
            name: string;
            /** @enum {string} */
            providerType: "openai-compatible";
            /** Format: uri */
            baseUrl: string;
            credentialRef: string;
            proxy?: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProviderDiagnosticStage: {
            /** @enum {string} */
            name: "configuration" | "credentials" | "model" | "generation";
            /** @enum {string} */
            status: "passed" | "failed";
            message: string;
            /** Format: int64 */
            latencyMs: number;
        };
        ProviderFailure: {
            /** @enum {string} */
            category: "configuration_invalid" | "credential_unavailable" | "endpoint_unreachable" | "authentication_failed" | "model_not_found" | "rate_limited" | "request_timeout" | "context_overflow" | "malformed_response" | "provider_internal_error" | "request_rejected" | "cancelled" | "unknown";
            message: string;
            retryable: boolean;
            requestId?: string;
        };
        ProviderDiagnostic: {
            providerId: string;
            modelProfileId?: string;
            modelName?: string;
            /** @enum {string} */
            status: "ready" | "failed";
            failure?: components["schemas"]["ProviderFailure"];
            stages: components["schemas"]["ProviderDiagnosticStage"][];
            /** Format: int64 */
            latencyMs: number;
            /** Format: date-time */
            testedAt: string;
        };
        ModelProfile: {
            id: string;
            providerId: string;
            modelName: string;
            displayName: string;
            contextWindow: number;
            maxOutputTokens: number;
            supportsVision: boolean;
            supportsToolUse: boolean;
            supportsThinking: boolean;
            isDefault: boolean;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PolicyProfile: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "tool" | "turn" | "vision" | "compaction";
            version: number;
            config: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "active" | "inactive";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ImageArtifact: {
            id: string;
            projectId: string;
            sessionId?: string;
            name: string;
            /** @enum {string} */
            kind: "image" | "image_attachment";
            /** @enum {string} */
            mimeType: "image/png" | "image/jpeg" | "image/gif";
            /** Format: int64 */
            sizeBytes: number;
            sha256: string;
            width?: number;
            height?: number;
            /** Format: date-time */
            createdAt: string;
        };
        ArtifactReference: {
            artifactId: string;
            name: string;
            /** @enum {string} */
            kind: "image" | "table" | "static_html" | "text" | "file";
            mimeType: string;
            /** Format: int64 */
            sizeBytes: number;
            sha256: string;
            width?: number;
            height?: number;
        };
        Artifact: {
            id: string;
            projectId: string;
            sessionId?: string;
            messageId?: string;
            runId?: string;
            name: string;
            /** @enum {string} */
            kind: "image" | "image_attachment" | "table" | "static_html" | "text" | "file";
            mimeType: string;
            /** Format: int64 */
            sizeBytes: number;
            sha256: string;
            width?: number;
            height?: number;
            sourceToolCallId?: string;
            sourceKind?: string;
            /** @enum {string} */
            retentionClass: "project";
            /** Format: date-time */
            createdAt: string;
        };
        TablePreview: {
            /** @enum {string} */
            format: "csv" | "tsv" | "xlsx";
            sheets?: string[];
            sheet?: string;
            columns: string[];
            rows: string[][];
            truncatedRows: boolean;
            truncatedColumns: boolean;
            /** @constant */
            rowLimit: 100;
            /** @constant */
            columnLimit: 30;
        };
        TextPreview: {
            text: string;
            truncated: boolean;
        };
        TurnContentPart: {
            /** @constant */
            type: "text";
            text: string;
        } | {
            /** @constant */
            type: "image";
            artifactId: string;
        };
        Project: {
            id: string;
            name: string;
            description: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectWorkspace: {
            id: string;
            projectId: string;
            /** @enum {string} */
            kind: "local";
            hostPath: string;
            /** @constant */
            virtualPath: "/workspace";
            status: string;
            pathFingerprint: string;
            /** Format: date-time */
            createdAt: string;
        };
        WorkspaceFileEntry: {
            name: string;
            path: string;
            isDir: boolean;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            modifiedAt: string;
        };
        Session: {
            id: string;
            projectId: string;
            title: string;
            /** @enum {string} */
            status: "active" | "archived";
            activeLeafMessageId?: string;
            activeBranchId?: string;
            defaultAgentProfileId?: string;
            defaultModelProfileId?: string;
            compactionPolicyProfileId?: string;
            sourceSessionId?: string;
            sourceMessageId?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SessionBranch: {
            id: string;
            sessionId: string;
            parentBranchId?: string;
            forkMessageId?: string;
            leafMessageId?: string;
            label: string;
            messageCount: number;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BranchNavigation: {
            session: components["schemas"]["Session"];
            branches: components["schemas"]["SessionBranch"][];
        };
        SessionMessagePage: {
            messages: components["schemas"]["Message"][];
            nextCursor?: string;
            hasMore: boolean;
            activeLeafMessageId?: string;
        };
        Message: {
            id: string;
            sessionId: string;
            parentMessageId?: string;
            /** @enum {string} */
            role: "user" | "assistant" | "tool";
            status: string;
            runId?: string;
            parts: components["schemas"]["MessageContentBlock"][];
            /** Format: date-time */
            createdAt: string;
        };
        MessageContentBlock: components["schemas"]["TextContentBlock"] | components["schemas"]["ThinkingContentBlock"] | components["schemas"]["ToolCallContentBlock"] | components["schemas"]["ToolResultContentBlock"] | components["schemas"]["ImageContentBlock"] | components["schemas"]["ImageDescriptionContentBlock"];
        TextContentBlock: {
            /** @constant */
            type: "text";
            text: string;
        };
        ThinkingContentBlock: {
            /** @constant */
            type: "thinking";
            text: string;
        };
        ToolCallContentBlock: {
            /** @constant */
            type: "tool_call";
            toolCall: {
                id: string;
                name: string;
                arguments: {
                    [key: string]: unknown;
                };
                argumentsFragment?: string;
                partial?: boolean;
            };
        };
        ToolResultContentBlock: {
            /** @constant */
            type: "tool_result";
            toolResult: {
                toolCallId: string;
                toolName: string;
                content: string;
                isError: boolean;
                artifacts?: components["schemas"]["ArtifactReference"][];
            };
        };
        ImageContentBlock: {
            /** @constant */
            type: "image";
            image: {
                artifactId: string;
                mimeType: string;
                sha256: string;
                width: number;
                height: number;
            };
        };
        ImageDescriptionContentBlock: {
            /** @constant */
            type: "image_description";
            imageDescription: {
                artifactId: string;
                text: string;
                modelId: string;
                promptVersion: string;
            };
        };
        RunEvent: {
            /** Format: int64 */
            eventId: number;
            runId: string;
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            type: "run_queued" | "run_started" | "context_warning" | "context_pruned" | "context_compaction_planned" | "context_compaction_started" | "context_compaction_retry_scheduled" | "context_compaction_retry_started" | "context_compaction_completed" | "context_compaction_failed" | "context_compaction_cancelled" | "context_checkpoint_selected" | "context_checkpoint_invalid" | "context_overflow_recovery_started" | "context_overflow_recovery_completed" | "run_context_compaction_planned" | "run_context_compaction_started" | "run_context_compaction_retry_scheduled" | "run_context_compaction_completed" | "run_context_compaction_failed" | "run_context_compaction_cancelled" | "model_route_selected" | "model_call_started" | "vision_fallback_started" | "vision_description_delta" | "vision_fallback_attempt_failed" | "vision_fallback_completed" | "vision_fallback_failed" | "model_call_attempt_failed" | "model_call_retry_scheduled" | "text_delta" | "thinking_delta" | "tool_call_delta" | "usage_updated" | "model_call_completed" | "model_call_failed" | "output_truncated" | "tool_call_started" | "tool_call_completed" | "tool_call_failed" | "tool_call_skipped" | "tool_policy_denied" | "tool_policy_terminated" | "tool_result_projected" | "approval_requested" | "approval_resolved" | "turn_stop_requested" | "stuck_tool_loop" | "message_committed" | "run_succeeded" | "run_failed" | "run_cancelled" | "run_interrupted";
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AgentRun: {
            id: string;
            turnId?: string;
            sessionId: string;
            /** @enum {string} */
            runKind: "agent" | "context_compaction";
            baseMessageId?: string;
            attempt: number;
            /** @enum {string} */
            status: "queued" | "running" | "waiting_for_approval" | "succeeded" | "failed" | "cancelled" | "interrupted";
            assistantMessageId?: string;
            retryOfRunId?: string;
            requestedConfig: {
                [key: string]: unknown;
            };
            effectiveConfig: {
                [key: string]: unknown;
            };
            errorCode?: string;
            errorMessage?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        RunRecovery: {
            run: components["schemas"]["AgentRun"];
            retryable: boolean;
            /** @enum {string} */
            blockedReason?: "active_run" | "inactive_turn" | "not_latest_attempt" | "projected_output" | "side_effect_boundary";
        };
        RunRetrySubmission: {
            sourceRunId: string;
            run: components["schemas"]["AgentRun"];
            existing: boolean;
        };
        ApprovalItem: {
            callIndex: number;
            toolCallId: string;
            toolName: string;
            /** @enum {string} */
            riskClass: "read_only" | "local_write" | "shell" | "external" | "sensitive";
            argumentsPreview: string;
        };
        ToolApprovalRequest: {
            id: string;
            runId: string;
            sessionId: string;
            iteration: number;
            batchDigest: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "cancelled";
            items: components["schemas"]["ApprovalItem"][];
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        ActiveRunState: {
            run: components["schemas"]["AgentRun"];
            pendingApproval?: components["schemas"]["ToolApprovalRequest"];
        };
        TurnSubmission: {
            turnId: string;
            userMessageId: string;
            run: components["schemas"]["AgentRun"];
            existing: boolean;
        };
        CompactionSubmission: {
            runId: string;
            compactionId: string;
            status: string;
            existing: boolean;
        };
        ContextCompaction: {
            id: string;
            runId?: string;
            sessionId: string;
            clientRequestId?: string;
            /** @enum {string} */
            status: "planned" | "running" | "completed" | "failed" | "cancelled";
            /** @enum {string} */
            reason: "manual" | "threshold" | "overflow";
            policyProfileId?: string;
            policyVersion?: number;
            requestedConfig: {
                [key: string]: unknown;
            };
            effectiveConfig: {
                [key: string]: unknown;
            };
            baseLeafMessageId: string;
            previousCompactionId?: string;
            sourceFromMessageId?: string;
            sourceThroughMessageId?: string;
            firstKeptMessageId: string;
            sourceDigest: string;
            summaryContractDigest: string;
            summary: string;
            summaryDigest: string;
            promptVersion: string;
            modelCallId?: string;
            tokensBefore: number;
            estimatedTokensAfter: number;
            reclaimedTokens: number;
            errorCode?: string;
            errorMessage?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        QueuedInput: {
            id: string;
            runId: string;
            sessionId: string;
            clientRequestId: string;
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            kind: "steer" | "follow_up";
            text: string;
            /** @enum {string} */
            status: "queued" | "injected" | "cancelled";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            injectedAt?: string;
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ProjectID: string;
        SessionID: string;
        RunID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worker is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    listProviderProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ProviderProfile"][];
                    };
                };
            };
        };
    };
    createProviderProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    providerType: "openai-compatible";
                    /** Format: uri */
                    baseUrl: string;
                    credentialRef: string;
                    proxy?: string;
                };
            };
        };
        responses: {
            /** @description Provider profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ProviderProfile"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    testProviderProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    modelProfileId?: string;
                };
            };
        };
        responses: {
            /** @description Ephemeral Provider diagnostic result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ProviderDiagnostic"];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listModelProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model profiles, with the explicit global default first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ModelProfile"][];
                    };
                };
            };
        };
    };
    createModelProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    providerId: string;
                    modelName: string;
                    displayName?: string;
                    contextWindow: number;
                    maxOutputTokens: number;
                    supportsVision?: boolean;
                    supportsToolUse?: boolean;
                    supportsThinking?: boolean;
                    isDefault?: boolean;
                };
            };
        };
        responses: {
            /** @description Model profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ModelProfile"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    setDefaultModelProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Explicit global default model profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ModelProfile"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listPolicyProfiles: {
        parameters: {
            query?: {
                kind?: "tool" | "turn" | "vision" | "compaction";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned policy profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PolicyProfile"][];
                    };
                };
            };
        };
    };
    createPolicyProfileVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    kind: "tool" | "turn" | "vision" | "compaction";
                    config: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Policy profile version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PolicyProfile"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    setDefaultPolicyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Global default policy for its kind */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PolicyProfile"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    deactivatePolicyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy profile deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Project"][];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string;
                    hostPath: string;
                };
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            project: components["schemas"]["Project"];
                            workspace: components["schemas"]["ProjectWorkspace"];
                        };
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getProjectWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active project workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ProjectWorkspace"];
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listProjectFiles: {
        parameters: {
            query?: {
                /** @description Project-relative virtual path rooted at /workspace */
                path?: string;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory entries, with directories first and names sorted case-insensitively */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["WorkspaceFileEntry"][];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    readProjectFile: {
        parameters: {
            query: {
                /** @description Project-relative virtual file path rooted at /workspace */
                path: string;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File bytes with detected MIME type and Range support */
            200: {
                headers: {
                    "X-Content-Type-Options"?: "nosniff";
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Requested byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            413: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /** @description Session lifecycle view; defaults to active */
                status?: "active" | "archived";
                /** @description Case-insensitive literal title substring within the selected Project */
                q?: string;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions in the requested lifecycle state, ordered by recent update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Session"][];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    defaultModelProfileId?: string;
                    compactionPolicyProfileId?: string;
                };
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    defaultModelProfileId?: string | null;
                    compactionPolicyProfileId?: string | null;
                };
            };
        };
        responses: {
            /** @description Session defaults updated; already frozen runs are unaffected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    archiveSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active Session archived without changing canonical history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    restoreSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived Session restored as active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listSessionMessages: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque cursor returned by the previous page; bound to the current Session and active branch */
                before?: string;
            };
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical messages from the active Session branch, ordered oldest to newest within the page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["SessionMessagePage"];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                artifactID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session-authorized immutable artifact metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Artifact"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    previewArtifact: {
        parameters: {
            query?: {
                /** @description Exact XLSX worksheet name; ignored for other artifact kinds */
                sheet?: string;
            };
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                artifactID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe preview selected by the stored artifact kind */
            200: {
                headers: {
                    "X-Content-Type-Options"?: "nosniff";
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TablePreview"] | components["schemas"]["TextPreview"];
                    };
                    "text/html": string;
                    "image/png": string;
                    "image/jpeg": string;
                    "image/gif": string;
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    downloadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                artifactID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original immutable artifact bytes served as an attachment */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "X-Content-Type-Options"?: "nosniff";
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listSessionBranches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable branch identities for this Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["SessionBranch"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createSessionBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    fromMessageId: string;
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Branch created from the active lineage and activated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["BranchNavigation"];
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    activateSessionBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
                branchID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing branch activated without rewriting messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["BranchNavigation"];
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getSessionRecovery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest active-lineage failed or interrupted Run recovery state, or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RunRecovery"] | null;
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getSessionActiveRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current non-terminal Run and its pending approval, or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ActiveRunState"] | null;
                    };
                };
            };
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    uploadImageAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    sessionId: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Managed image artifact */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ImageArtifact"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    submitTurn: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text?: string;
                    content?: components["schemas"]["TurnContentPart"][];
                    baseMessageId?: string;
                    config?: {
                        modelProfileId?: string;
                        candidateModelProfileIds?: string[];
                        allowAutoRoute?: boolean;
                        toolPolicyProfileId?: string;
                        turnPolicyProfileId?: string;
                        visionPolicyProfileId?: string;
                        compactionPolicyProfileId?: string;
                        maxIterations?: number;
                        /** @enum {string} */
                        toolExecution?: "sequential" | "safe_parallel";
                        maxConcurrentReadTools?: number;
                    };
                } | unknown | unknown;
            };
        };
        responses: {
            /** @description Existing idempotent submission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TurnSubmission"];
                    };
                };
            };
            /** @description Turn accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TurnSubmission"];
                    };
                };
            };
            409: components["responses"]["Error"];
        };
    };
    listContextCompactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session context checkpoints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ContextCompaction"][];
                    };
                };
            };
        };
    };
    createContextCompaction: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    baseMessageId: string;
                    clientRequestId?: string;
                    instructions?: string;
                };
            };
        };
        responses: {
            /** @description Existing idempotent submission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CompactionSubmission"];
                    };
                };
            };
            /** @description Manual context compaction accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CompactionSubmission"];
                    };
                };
            };
            409: components["responses"]["Error"];
        };
    };
    getContextCompaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compactionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Context checkpoint detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ContextCompaction"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AgentRun"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    retryRun: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    clientRequestId?: string;
                };
            };
        };
        responses: {
            /** @description Existing idempotent retry submission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RunRetrySubmission"];
                    };
                };
            };
            /** @description Safe retry attempt created and queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RunRetrySubmission"];
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run cancelled or already terminal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AgentRun"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    queueRunInput: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "steer" | "follow_up";
                    text: string;
                    clientRequestId?: string;
                };
            };
        };
        responses: {
            /** @description Input queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["QueuedInput"];
                    };
                };
            };
            409: components["responses"]["Error"];
        };
    };
    decideToolApproval: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                approvalID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approved" | "rejected";
                    clientRequestId?: string;
                };
            };
        };
        responses: {
            /** @description Approval decision stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ToolApprovalRequest"];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                runID: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replayable server-sent event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
